project_id = "hmmbspebnqkueqwcqinr"

[functions.weekly-progress-email]
verify_jwt = false

[functions.send-push-notifications]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.admin-push]
verify_jwt = false

[functions.event-reminders]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false
